        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 27 01:41:32 2015
        MODULE ALLOC_SOL_ARRAY_1D__genmod
          INTERFACE 
            SUBROUTINE ALLOC_SOL_ARRAY_1D
            END SUBROUTINE ALLOC_SOL_ARRAY_1D
          END INTERFACE 
        END MODULE ALLOC_SOL_ARRAY_1D__genmod
