        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 27 01:41:32 2015
        MODULE CONPQ1_1D__genmod
          INTERFACE 
            SUBROUTINE CONPQ1_1D(Q)
              REAL(KIND=8) :: Q(3)
            END SUBROUTINE CONPQ1_1D
          END INTERFACE 
        END MODULE CONPQ1_1D__genmod
