        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 27 01:41:32 2015
        MODULE EULER_1D__genmod
          INTERFACE 
            SUBROUTINE EULER_1D
            END SUBROUTINE EULER_1D
          END INTERFACE 
        END MODULE EULER_1D__genmod
