        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 27 01:41:32 2015
        MODULE RINPUT_1D__genmod
          INTERFACE 
            SUBROUTINE RINPUT_1D
            END SUBROUTINE RINPUT_1D
          END INTERFACE 
        END MODULE RINPUT_1D__genmod
