        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 27 01:41:32 2015
        MODULE SET_DIMEN_1D__genmod
          INTERFACE 
            SUBROUTINE SET_DIMEN_1D
            END SUBROUTINE SET_DIMEN_1D
          END INTERFACE 
        END MODULE SET_DIMEN_1D__genmod
